@rem Gradle wrapper generated by AgentFactory
@echo off
setlocal

set DIRNAME=%~dp0
if "%DIRNAME%"=="" set DIRNAME=.
set APP_BASE_NAME=%~n0
set APP_HOME=%DIRNAME%

set WRAPPER_JAR=%APP_HOME%\gradle\wrapper\gradle-wrapper.jar
set WRAPPER_PROPS=%APP_HOME%\gradle\wrapper\gradle-wrapper.properties
set WRAPPER_URL=https\://services.gradle.org/distributions/gradle-8.7-bin.zip

if not exist "%WRAPPER_JAR%" (
    echo Downloading Gradle wrapper JAR...
    powershell -Command "& { Invoke-WebRequest -Uri 'https\://raw.githubusercontent.com/gradle/gradle/v8.7.0/gradle/wrapper/gradle-wrapper.jar' -OutFile '%WRAPPER_JAR%' }" 2>nul
    if exist "%WRAPPER_JAR%" (
        echo Gradle wrapper JAR downloaded successfully.
    ) else (
        echo ERROR: Could not download Gradle wrapper JAR.
        echo Please install Gradle manually and run: gradle wrapper
        exit /b 1
    )
)

if not exist "%WRAPPER_PROPS%" (
    echo ERROR: gradle-wrapper.properties not found.
    exit /b 1
)

"%JAVA_HOME%/bin/java.exe" -Dorg.gradle.appname=%APP_BASE_NAME% -classpath "%WRAPPER_JAR%" org.gradle.wrapper.GradleWrapperMain %*
if %errorlevel% neq 0 exit /b %errorlevel%

endlocal
